# Generated by Django 4.2.6 on 2023-10-17 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('Nom_societe', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=100)),
                ('competence', models.CharField(max_length=100)),
                ('formation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publication', models.BooleanField(default=False)),
                ('date_limite', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='icon_about.png', upload_to='uploaded_images/')),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
