# Generated by Django 4.2.6 on 2023-11-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_systeme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=50)),
                ('email_user', models.EmailField(max_length=254)),
                ('cv_file', models.FileField(upload_to='cvs')),
                ('lettre', models.TextField()),
                ('Etat', models.BooleanField(default=False, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('numero_offre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application_systeme.offre')),
            ],
        ),
    ]
