# Generated by Django 4.2.6 on 2023-11-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_systeme', '0002_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.CharField(max_length=50)),
                ('Poste', models.CharField(max_length=50)),
                ('date_postuler', models.CharField(max_length=50, null=True)),
                ('Etat', models.CharField(default='En cours', max_length=50)),
                ('numero_offre', models.IntegerField(null=True)),
            ],
        ),
    ]
