# Generated by Django 4.2.6 on 2023-11-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_systeme', '0003_postulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomCandidat', models.CharField(max_length=50)),
                ('email_candidat', models.CharField(max_length=50)),
                ('Titre_offre', models.CharField(max_length=50)),
                ('Score', models.IntegerField(null=True)),
                ('cv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application_systeme.cv')),
            ],
        ),
    ]
